services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: deppi_db_user
      POSTGRES_PASSWORD: Dge4NqXSn06IJxvCOYE0qvbPvbeBKjic
      POSTGRES_DB: deppi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:
